apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mongodb-deployment
  namespace: default
  labels:
    app:  mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app:  mongodb
    spec:
      containers:
      - name:  mongodb
        image:  mongo
        ports:
          - containerPort:  27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value:
        - name: MONGO_INITDB_ROOT_PASSWORD
